name: RetrieveFactsPipeline

on:
  schedule:
    - cron: "0 5,11,16,20 * * *" 
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: RepositoryCheckout
        uses: actions/checkout@v3

      - name: PythonSetup
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: DebugRequirements
        run: cat requirements.txt

      - name: DependenciesInstallation
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: PipelineRun
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python srcEngineering/RetrieveFacts.py